Add KMS module
alibabacloud-automation/terraform-alicloud-kms pull request #1
Opened 2020-03-05 08:08 UTC by Rich-yi

2020-03-05 08:20 UTC, zql-tqy commented on README-CN.md
> +本 Terraform 模块将用于在阿里云上创建KMS。
建议中文里的英文左右两边各加一个空格

2020-03-05 08:20 UTC, zql-tqy commented on README-CN.md
> +
中文的readme中没有支持创建的资源吧

2020-03-05 08:20 UTC, zql-tqy commented on README.md
> +-> **NOTE:** At present, the resource only supports to modify `is_enabled`.
这个在中文的readme中也没有吧

2020-03-05 08:20 UTC, zql-tqy commented on varibales.tf
> +  description = "Whether to create kms key resource. Defalult to true."
default写错了

2020-03-05 08:20 UTC, zql-tqy commented on varibales.tf
> +  description = "Duration in days after which the key is deleted after destruction of the resource, must be between 7 and 30 days. Defaults to 30 days."
这个也是default

2020-03-05 08:20 UTC, zql-tqy commented on README-CN.md
> +  profile                    = "Your-Profile-Name"
这个格式调一下吧

2020-03-09 12:48 UTC, xiaozhu36 requested changes

2020-03-09 12:48 UTC, xiaozhu36 commented on main.tf
> +  plaintext          = var.plaintext
这个resource也需要开关

2020-03-09 12:48 UTC, xiaozhu36 commented on varibales.tf
> +variable "create_instance" {
create_kms

2020-03-09 12:48 UTC, xiaozhu36 commented on varibales.tf
> +variable "key_id" {
existing_key_id
再加一个 use_existing_key

2020-03-10 12:35 UTC, xiaozhu36 requested changes

2020-03-10 12:35 UTC, xiaozhu36 commented on main.tf
> +  count                   = var.existing_key_id != "" ? 0 : var.create_kms ? 1 : 0
这个count应该用 use_existing_key 来控制

2020-03-10 12:35 UTC, xiaozhu36 commented on main.tf
> +resource "alicloud_kms_ciphertext" "kms" {
这个资源应该要跟 key_usage 具体的值对应起来吧

2020-03-14 03:08 UTC, xiaozhu36 requested changes

2020-03-14 03:08 UTC, xiaozhu36 commented on varibales.tf
> +variable "create_kms_ciphertext" {
create_kms_ciphertext 改成 encrypt
description = "Whether to encrypt plaintext. Default to true."

2020-03-14 03:08 UTC, xiaozhu36 commented on main.tf
> +  key_id             = local.this_kms_key_id
这个是加密的resource，还要支持一个解密的resource

2020-03-16 11:02 UTC, xiaozhu36 approved these changes

2020-03-16 11:02 UTC, merged